### PR TITLE
Added DeathNote Anime

### PR DESCRIPTION
**Pull request by DhanushNehru**

### CODE REVIEW

**Comment by 44jax44** [comment]
Hey can you put your Twitter handle in there? as this is your own point of view, so people can add their own point of view under it and so on

**Comment by DhanushNehru** [comment]
Can you specify exactly where should I embed my twitter handle ?

**Comment by 44jax44** [comment]
Yea when you add "why should people watch it or not?"  the idea for this to act as a review from your side, so just add your Twitter handle at the end of your "review" and later on if we make some cool design for it, it looks cool being your own opinion and so on

**Review by DhanushNehru — COMMENTED** [review]
Added twitter handle

**Pull request merged**
